### PR TITLE
fix(chat): cancel run

### LINKED ISSUE #75: User message disappears when stopping assistant
## Description 
Stopping agent with stop button makes user message disappear.
image

## To Reproduce
1. Open new conversation
2. Say "Hi" or anything else
3. Click stop before the agent responds

## Expected behavior
User message does not disappear

Reproduced on Dev

### PR DESCRIPTION
**Pull request by kapetr**
Closes #75

### CODE REVIEW

File: src/modules/chat/api/useDeleteMessage.ts [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+import { useMutation, useQueryClient } from '@tanstack/react-query';
+import { deleteMessage } from '@/app/api/threads-messages';
+import { useProjectContext } from '@/layout/providers/ProjectProvider';
+import { messagesWithFilesQuery } from '../queries';
+
+export function useDeleteMessage({ onSuccess }: { onSuccess?: () => void }) {
```
Comment (PetrBulanek) [inline src/modules/chat/api/useDeleteMessage.ts:22]: You pass prop onSuccess, but you don't actually call the function.

File: src/modules/chat/assistant-plan/PlanWithSources.tsx [hunk 2]
```diff
@@ -108,6 +112,27 @@ function PlanWithSourcesComponent({ message, inView }: Props) {
...
+      steps.some((step) => {
+        if (step.status === 'in_progress') {
+          const lastToolCall = step.toolCalls.at(-1);
+          if (lastToolCall) {
+            const toolApproval = getToolApproval(lastToolCall, message.run);
+            return Boolean(toolApproval);
+          }
+        }
+        return false;
+      })
```
Comment (PetrBulanek) [inline src/modules/chat/assistant-plan/PlanWithSources.tsx:130]: I'd probably set it to a variable with a descriptive name to make it a bit clearer to understand.

File: src/modules/chat/providers/ChatProvider.tsx [hunk 3]
```diff
@@ -162,8 +164,13 @@ export function ChatProvider({
   const queryClient = useQueryClient();
   const threadSettingsButtonRef = useRef<HTMLButtonElement>(null);
 
+  const { mutateAsync: mutateDeleteMessage } = useDeleteMessage({});
```
Comment (PetrBulanek) [inline src/modules/chat/providers/ChatProvider.tsx:167]: You can set the empty object as the default parameter so that you don't have to pass it here.

File: src/modules/chat/api/useDeleteMessage.ts (hunk 1 above)
Comment (kapetr) [reply src/modules/chat/api/useDeleteMessage.ts:22]: Removing for now, it is not used.
